# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuGvQejleOIKq5BSe69uwC3-9kAbTX5z
"""

import gdown

# ID directo del archivo extraído del folder
direct_file_id = '1LUnhR27-PExeNYqZlMxzICJ3UYBXPozx'
url = f'https://drive.google.com/uc?id={direct_file_id}'
output = 'RVE 303-26.pdf'

gdown.download(url, output, quiet=False)

# ==========================================
# 0. SETUP E INSTALACIÓN DE LIBRERÍAS
# ==========================================
!pip install -q chromadb langchain-chroma langchain-huggingface langchain-community rank_bm25 sentence-transformers langchain-groq langchain-classic

import re
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers import EnsembleRetriever

# ==========================================
# 1. CONTENIDO DE LA RESOLUCIÓN
# ==========================================
full_text = """
1. Publicidad Gráfica
Toda publicidad de casinos físicos y apuestas en línea difundidas a través de internet, plataformas de medios o redes sociales, cartelería en la vía pública, medios o plataformas de difusión gráfica, deberá incluir las leyendas "SOLO PARA MAYORES DE 18 AÑOS" Y "EL JUGAR COMPULSIVAMENTE ES PERJUDICIAL PARA LA SALUD", ambas en los términos establecidos en el presente, y junto al logo de LOTERÍA DE SANTA FE. Las leyendas establecidas, deberán ser proporcionadas dentro del espacio destinado a la pieza publicitaria, ocupando al pie de la misma, la totalidad de su espacio horizontal, y con una altura igual o mayor al 10% de la altura total del anuncio.

2. Publicidad radial
En publicidades emitidas por medios radiales, sólo será obligatoria la leyenda "SOLO PARA MAYORES DE 18 AÑOS ES UN MENSAJE DE LOTERÍA DE SANTA FE" que deberá estar al finalizar el anuncio, debiendo ser locutada en forma clara, sin música de fondo, audible y comprensible, no pudiendo ser la misma más veloz, en comparación con el texto locutado en el cuerpo principal del anuncio.

3. Publicidad por videos
Cuando la publicidad sea emitida en medios televisivos o digitales o de cualquier otro formato mediante la difusión de video el mismo deberá contener los anuncios conforme lo previsto en el punto 1 (publicidad gráfica) durante el tiempo que dure el video y, agregar al finalizar una placa con la imagen centrada de las leyendas y logo de Lotería de Santa Fe detallado en el punto 1.

4. Pauta no tradicional
La publicidad que se realice oralmente mediante P.N.T. o mediante influencers, actores o periodistas deberá finalizar con la leyenda prevista en el punto 2 en los términos allí previstos, o bien agregando las leyendas del punto 1 durante todo el tiempo que se esté haciendo alusión a la modalidad de participación Y/O acceso a los sitios de juegos y apuestas.

5. Publicidad en espacios alternativos
En aquellas publicidades gráficas que no sea posible la colocación del zócalo previsto en el punto 1 (por ejemplo camisetas o vestimenta en general), se deberá ubicar debajo de la marca de la empresa ocupando dos renglones la leyenda "SOLO PARA MAYORES DE 18 AÑOS" y junto a la misma el logo de LOTERÍA DE SANTA FE.

6. Otra publicidad
En caso que la publicidad no quede encuadrada en ninguno de los anteriores el operador deberá comunicarse previamente con Lotería de Santa Fe para conocer cómo debe realizar la propuesta.
"""

# ==========================================
# 2. CHUNKING CONTROLADO POR PUNTOS NORMATIVOS
# ==========================================
# Separamos limpiamente usando los identificadores numéricos del documento real
parts = re.split(r'(?=\n\s*\d+\.\s+)', full_text)
parts = [p.strip() for p in parts if p.strip()]

docs = []
for p in parts:
    # Extraemos el número y la primera línea como título semántico
    lines = p.split('\n')
    header_line = lines[0]

    match_num = re.match(r'^(\d+)\.', header_line)
    art_num = int(match_num.group(1)) if match_num else 0

    docs.append(Document(
        page_content=p,
        metadata={'art': art_num, 'titulo': header_line}
    ))

print(f"✓ {len(docs)} puntos normativos procesados y chunkedos.")

# ==========================================
# 3. GENERACIÓN DE EMBEDDINGS E INDEXACIÓN
# ==========================================
model_name = 'paraphrase-multilingual-MiniLM-L12-v2'
emb = HuggingFaceEmbeddings(model_name=model_name)

# Guardamos en ChromaDB local
vector_store = Chroma.from_documents(docs, emb, collection_name='rve_303_26')
print(f"✓ Chunks indexados con éxito en ChromaDB.")

# =====================================================================
# 4. CONFIGURACIÓN DEL PIPELINE HÍBRIDO (Corregido con k=3)
# =====================================================================
# Subimos k a 3 para garantizar que el LLM reciba suficiente contexto normativo
dense_retriever = vector_store.as_retriever(search_kwargs={'k': 3})

bm25_retriever = BM25Retriever.from_documents(docs)
# Subimos k a 3 también en el recuperador léxico BM25
bm25_retriever.k = 3

# Fusión híbrida estable
hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, dense_retriever],
    weights=[0.5, 0.5]
)
print("✓ Pipeline Híbrido optimizado con k=3 para evitar pérdidas de contexto.")

# =====================================================================
# 1. SETUP DE MODELO (Groq) Y DEPENDENCIAS DE LANGGRAPH
# =====================================================================
import os
import json
from typing import TypedDict
from google.colab import userdata
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, START, END

# Configuración segura de credenciales de la clase
try:
    os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
    print("✓ GROQ_API_KEY configurada desde los Secrets de Colab.")
except Exception:
    print("⚠ Alerta: Recordá setear tu GROQ_API_KEY en la barra de la izquierda.")

# Inicializamos el LLM oficial del curso
llm = ChatGroq(
    model='llama-3.3-70b-versatile',
    temperature=0.1,  # Temperatura baja para asegurar veredictos estrictos y consistentes
)

# Helper para llamadas directas al modelo
def _llm(system: str, user: str) -> str:
    resp = llm.invoke([SystemMessage(content=system), HumanMessage(content=user)])
    return resp.content

# =====================================================================
# 2. ESTADO COMPARTIDO DEL EQUIPO (TypedDict de Clase)
# =====================================================================
class EstadoEvaluacion(TypedDict):
    solicitud_id: str
    tipo_medio: str               # "grafica", "radial", "video", "pnt"
    archivo_contenido: str        # Transcripción de audio, descripción de imagen o texto plano
    articulos_legales: str        # Contexto dinámico inyectado desde el RAG
    reporte_especialista: str     # Informe analítico en Lenguaje Natural del sub-agente
    veredicto_final: str          # APROBAR, RECHAZAR o REVISAR
    justificacion_final: str      # Síntesis estructurada para el veredicto

# =====================================================================
# 3. DEFINICIÓN DE LOS NODOS (Flujo Multi-Agente)
# =====================================================================
def nodo_orquestador_rag(state: EstadoEvaluacion) -> dict:
    print(f"\n[ORQUESTADOR] Planificando evaluación para la Solicitud {state['solicitud_id']}")

    # QUERY OPTIMIZADA: Buscamos la palabra clave exacta (ej: "Publicidad radial" o "Publicidad Gráfica")
    query_busqueda = f"Publicidad {state['tipo_medio']}"

    chunks_recuperados = hybrid_retriever.invoke(query_busqueda)
    contexto_ley = "\n\n".join([f"[{c.metadata['titulo']}]: {c.page_content}" for c in chunks_recuperados])

    print("✓ [ORQUESTADOR] Marco normativo recuperado y mapeado al Estado.")
    return {"articulos_legales": contexto_ley}


def nodo_especialista_legal(state: EstadoEvaluacion) -> dict:
    """Sub-Agente Orquestado: Procesa el lenguaje natural contrastando el RAG contra el contenido."""
    print(f"[ESPECIALISTA] Evaluando compatibilidad normativa mediante PLN cognitivo...")

    system_prompt = """
    Sos un inspector técnico y auditor legal de la Lotería de Santa Fe. Tu único rol es contrastar el contenido de la publicidad contra el marco regulatorio provisto.
    Analizá detalladamente si la pieza publicitaria cumple o si infringe la norma.

    REGLA DE ORO: Sé riguroso y formal. No inventes regulaciones. Basate ESTRICTAMENTE en las cláusulas provistas en el contexto.
    """

    user_prompt = f"""
    Normativa aplicable vigente (Inyectada dinámicamente desde el RAG):
    {state['articulos_legales']}

    Contenido del material promocional a evaluar (Extraído por el procesador de archivos):
    {state['archivo_contenido']}

    Redactá un informe técnico detallando las concordancias detectadas o listando taxativamente cada una de las infracciones normativas encontradas.
    """

    reporte_pln = _llm(system=system_prompt, user=user_prompt)
    print("✓ [ESPECIALISTA] Informe normativo consolidado en el Estado.")
    return {"reporte_especialista": reporte_pln}


def nodo_emisor_veredicto(state: EstadoEvaluacion) -> dict:
    """Orquestador (Cierre): Analiza las conclusiones del especialista y dicta la sentencia estructurada."""
    print("[ORQUESTADOR] Analizando informe técnico para emitir dictamen de cierre...")

    system_prompt = """
    Sos el juez de control y director administrativo de la Lotería de Santa Fe. Tu rol es revisar el informe del inspector técnico y emitir una resolución definitiva.
    Tu respuesta debe seguir OBLIGATORIAMENTE este formato estructurado:

    VEREDICTO: [Colocá únicamente una de estas opciones: APROBAR, RECHAZAR o REVISAR]
    JUSTIFICACIÓN: [Escribí una síntesis clara de máximo 3 oraciones, fundamentando la decisión en base al Anexo I]
    """

    user_prompt = f"Informe del inspector técnico:\n{state['reporte_especialista']}"

    dictamen_final = _llm(system=system_prompt, user=user_prompt)

    # Parseo adaptativo del veredicto para mapear el campo del estado compartido
    veredicto_limpio = "RECHAZAR" if "RECHAZAR" in dictamen_final else "APROBAR" if "APROBAR" in dictamen_final else "REVISAR"

    print("✓ [ORQUESTADOR] Dictamen final firmado y cargado al Estado.")
    return {"veredicto_final": veredicto_limpio, "justificacion_final": dictamen_final}

# =====================================================================
# 4. CONSTRUCCIÓN Y COMPILACIÓN DEL GRAFO (LangGraph)
# =====================================================================
workflow = StateGraph(EstadoEvaluacion)

# Agregamos los nodos al grafo tipado
workflow.add_node("orquestador_inicial", nodo_orquestador_rag)
workflow.add_node("sub_agente_especialista", nodo_especialista_legal)
workflow.add_node("orquestador_cierre", nodo_emisor_veredicto)

# Conectamos las aristas para formar el flujo lineal e interactivo de la cátedra
workflow.add_edge(START, "orquestador_inicial")
workflow.add_edge("orquestador_inicial", "sub_agente_especialista")
workflow.add_edge("sub_agente_especialista", "orquestador_cierre")
workflow.add_edge("orquestador_cierre", END)

# Compilamos el sistema multi-agente
app = workflow.compile()
print("\n✓ [SISTEMA] ¡Flujo Multi-Agente en LangGraph compilado y listo para pruebas!")

# Invocamos el flujo compartiendo el estado inicial
resultado_grafo = app.invoke({
    "solicitud_id": "SOL-2026-RAD-005",
    "tipo_medio": "radial",
    "archivo_contenido": "Transcripción del Audio promocional: '¡Ganar nunca fue tan fácil! Ingresá a nuestra web y empezá a jugar con las mejores cuotas'. Al finalizar la locución del anuncio principal, se escucha música pop electrónica de fondo con volumen alto mientras una voz en off enuncia de forma veloz: 'Solo para mayores de 18 años es un mensaje de Lotería de Santa Fe'."
})

# Separador estructurado para la consola de Colab
sep = "=" * 70

print(sep)
print("1. MARCO NORMATIVO MAPEADO DINÁMICAMENTE POR EL RAG:")
print(sep)
print(resultado_grafo["articulos_legales"])

print("\n" + sep)
print("2. INFORME DE PROCESAMIENTO COGNITIVO DEL SUB-AGENTE (PLN):")
print(sep)
print(resultado_grafo["reporte_especialista"])

print("\n" + sep)
print("3. VEREDICTO FINAL CONSOLIDADO POR EL ORQUESTADOR:")
print(sep)
print(resultado_grafo["justificacion_final"])