// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupTemporaryFiles():Promise<void>;

export function ExecuteAgent(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function SaveTemporaryFile(arg1:string,arg2:Array<number>):Promise<Record<string, any>>;
