// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupTemporaryFiles() {
  return window['go']['main']['App']['CleanupTemporaryFiles']();
}

export function ExecuteAgent(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveTemporaryFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTemporaryFile'](arg1, arg2);
}
