// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<number>;

export function CleanupTemporaryFiles():Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function ExecuteAgent(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAgentLogs():Promise<string>;

export function GetRules():Promise<Array<main.Rule>>;

export function Greet(arg1:string):Promise<string>;

export function SaveTemporaryFile(arg1:string,arg2:Array<number>):Promise<Record<string, any>>;

export function ToggleRule(arg1:number,arg2:boolean):Promise<void>;

export function UpdateRule(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:boolean):Promise<void>;
