// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3, arg4, arg5);
}

export function CleanupTemporaryFiles() {
  return window['go']['main']['App']['CleanupTemporaryFiles']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function ExecuteAgent(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2);
}

export function GetAgentLogs() {
  return window['go']['main']['App']['GetAgentLogs']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveTemporaryFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTemporaryFile'](arg1, arg2);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}

export function UpdateRule(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateRule'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
